version: "3.7"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www/laravel
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=123456
            - REDIS_HOST=redis
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: pos-db
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=123456
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d

    redis:
        image: redis:5.0-alpine
        ports:
            - "6379:6379"

volumes:
    dbdata:
