version: "3.7"

services:
  app:
    build:
      context: .
    container_name: pos_app
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: pos
      DB_USERNAME: pos
      DB_PASSWORD: 123456
    ports:
      - "9000:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: pos_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: pos
      MYSQL_USER: pos
      MYSQL_PASSWORD: 123456

volumes:
  mysql-data:
